# ----
# Site

title: "Cockburn Advisory Services Ltd"
url: "https://cockburnadvisory.co.uk"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "Contact details and information site for Cockburn Advisory."

author:
  name: "Dug Falby"
  email: dug@cockburnadvisory.co.uk
  twitter: dug # twitter username without the @ symbol

social:
  name: "Cockburn is using Cloud Cannon's Hydra template for Jekyll"
  links:
    - https://github.com/lrdj/cockburn

# -----
# Build

timezone: UTC+01:00

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS


_comments:
  map: Edinburgh
  latitude: 55.953252
  longitude: -3.188267
  zoom: 
  pricing_table: 
  highlight: 
  color: 
  new_window: 
